name: c_pdf
description: " project of pdf report."
 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
 
version: 1.0.0+1

environment:
  sdk: '>=3.2.1<4.0.0'
 
dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  universal_html: ^2.3.0
  pdf: ^3.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^5.0.0
 
flutter:
 
  uses-material-design: true
 